name: Create releases
"on":
  push:
    branches:
      - main
jobs:
  create-sentry-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1
      - name: Create a Sentry.io release
        uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          tagName: ${{ steps.package.outputs.name }}@${{ steps.package.outputs.version }}
          environment: ${{ secrets.SENTRY_ENVIRONMENT }}
